name: secrets practice
on: push
jobs:
  aws:
     runs-on: ubuntu-latest
     steps:
        - run: echo "my aws access key is ${{ secrets.AWS_ACCESS_KEY_ID }}"
        - run: echo "my aws secret key is ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
