name : Multoi job example
on: push
env:
  APP_NAME: my-app
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Building app..."
  test:
     needs: build
     runs-on: ubuntu-latest
     steps:
        - run: echo "Running tests..."
